#!/bin/bash

# Script to automatically detect and configure environment variables
# for Docker Compose to work on different machines

echo "🔍 Detecting system configuration..."

# Detect Docker group ID
DOCKER_GID=$(getent group docker | cut -d: -f3)
if [ -z "$DOCKER_GID" ]; then
    echo "❌ Docker group not found! Please install Docker first."
    exit 1
fi

# Detect current user ID
USER_ID=$(id -u)

# Detect if user is in docker group
if ! groups $USER | grep -q docker; then
    echo "⚠️  Current user is not in the docker group."
    echo "   Run: sudo usermod -aG docker $USER"
    echo "   Then logout and login again."
fi

echo "📋 Detected configuration:"
echo "   Docker Group ID: $DOCKER_GID"
echo "   User ID: $USER_ID"

# Create .env file with detected values
cat > .env << EOF
# Environment variables for Docker Compose
# This file is auto-generated by setup-env.sh - do not edit manually

# Docker group ID (auto-detected)
DOCKER_GID=$DOCKER_GID

# User ID (auto-detected)
USER_ID=$USER_ID

# MCP Server configuration
MCP_SERVER_PORT=8000
DASHBOARD_PORT=3000
TRAEFIK_PORT=8080

# Generated on: $(date)
EOF

echo "✅ Environment file created: .env"
echo "🚀 You can now run: docker compose up -d"